---
- import_playbook: pre-requisites.yaml

- import_playbook: haproxy.yaml

- import_playbook: setup-k8s-cluster.yaml

- import_playbook: deploy-manifest.yaml

- import_playbook: after-install.yaml



