- name: Generated token - 1.
  local_action: shell sed -n 73,75p ./token > ./mastertoken

- name: Copy master token
  become: true
  copy:
    src: ./mastertoken
    dest: /tmp/join-command.sh
    owner: root
    group: root
    mode: '0777'

- name: Add new Kubernetes master member
  become: true
  command: sh /tmp/join-command.sh