---
- name: comment disabled_plugins = ['cri'] in /etc/containerd/config.toml
  become: true
  replace:
      path: /etc/containerd/config.toml
      regexp: '^disabled_plugins'
      replace: '#disabled_plugins'

- name: Restart containerd service 
  become: true
  systemd:
    name: containerd
    state: restart


- name: Letting iptables see bridged traffic
  become: true
  copy:
    src: ./files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Reload sysctl config for iptables
  become: true
  shell: sysctl --system

- name: Disable SWAP
  become: true
  shell: swapoff -a

- name: Google Cloud public signing key
  become: true
  shell: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg


- name: Add the Kubernetes apt repository
  become: true
  shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Install kubeadm kubelet kubectl packages
  become: true
  apt: 
    name: 
    - kubeadm
    - kubelet
    - kubectl 
    state: latest
    update_cache: yes

