- name : Remove resolv.conf
  file: 
    path: /etc/resolv.conf
    state: absent
  become: true 

- name: Set DNS
  shell: |
    echo nameserver 185.51.200.2 >> /etc/resolv.conf
    echo nameserver 8.8.8.8 >> /etc/resolv.conf
  become: true
