---
- name: Generated token - 1.
  local_action: shell sed -n 82,84p ./token > ./workertoken

- name: Copy master token
  become: true
  copy:
    src: ./workertoken
    dest: /tmp/join-worker-command.sh
    owner: root
    group: root
    mode: '0777'

- name: Add new Kubernetes worker to cluster
  become: true
  command: sh /tmp/join-worker-command.sh