---
- name: Add Docker GPG apt Key
  become: true
  shell: 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg'

- name: Add Docker Repository
  become: true
  shell: 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable" | tee /etc/apt/sources.list.d/docker.list'

- name: Update apt and install docker-ce
  become: true
  apt: 
    name: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    state: latest
    update_cache: yes

- name: adding existing user ubuntu to group docker
  become: true
  user:
    name: ubuntu 
    groups: docker
    append: yes

