---
- name: Initializing Kubernetes cluster
  become: true
  shell: kubeadm init --control-plane-endpoint="192.168.8.100:6443" --upload-certs --apiserver-advertise-address {{ansible_eth1.ipv4.address}} --pod-network-cidr 192.168.0.0/16 
  register: output

- name: Storing Logs and Generated token for future purpose.
  local_action: copy content={{ output.stdout }} dest="./token"

- name: Copying required files
  become: true
  shell: |
    mkdir -p /home/debian/.kube
    sudo cp -f /etc/kubernetes/admin.conf /home/debian/.kube/config
    sudo chown 1000:1000 /home/debian/.kube/config

- name: Install calico pod network
  command: kubectl create -f https://docs.projectcalico.org/v3.22/manifests/calico.yaml